# INFRASTRUCTURE -------------------------------------------------------------

infra:
  terraform_s3_bucket: # secret
  terraform_s3_prefix: # secret
  server_hostname: # secret
  server_location: # secret
  server_type: # secret
  server_image: # secret

persistent_volume_id: # secret

zfs_pool: # secret
zfs_arc_memory: # secret


# ADMIN ----------------------------------------------------------------------

admin_user: # secret
admin_password: # secret
admin_password_salt: # secret
admin_public_keys: # secret


# VPN ------------------------------------------------------------------------

wireguard_network: # secret
wireguard_port: # secret
wireguard_nodes: # secret


# POSTGRESQL -----------------------------------------------------------------

postgres_password: # secret
postgres_databases: # secret
